@php($detail = $aboutPage?->venueDetail)
<div class="bo-form-section"><div class="bo-form-list">
    @include('backoffice.about-pages._main_page_select')
    <div class="bo-form-row"><label for="subtitle" class="bo-form-label">Sub Title</label><div class="bo-form-field"><textarea class="board-form-control board-form-textarea @error('subtitle') is-invalid @enderror" id="subtitle" name="subtitle" rows="10" data-backoffice-ckeditor data-source-editing="true">{{ old('subtitle', $aboutPage?->subtitle) }}</textarea>@error('subtitle')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
    <div class="bo-form-row"><label for="postal_code" class="bo-form-label">포럼 위치</label><div class="bo-form-field"><div class="input-with-button bo-gap-bottom"><input type="text" class="board-form-control bo-address-postcode @error('postal_code') is-invalid @enderror" id="postal_code" name="postal_code" value="{{ old('postal_code', $detail?->postal_code) }}" maxlength="20" placeholder="우편번호" readonly><button type="button" class="btn btn-secondary btn-sm" data-venue-address-search>검색</button></div><input type="text" class="board-form-control @error('address') is-invalid @enderror" id="address" name="address" value="{{ old('address', $detail?->address) }}" maxlength="500" placeholder="기본주소" readonly>@error('postal_code')<div class="invalid-feedback">{{ $message }}</div>@enderror @error('address')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
    <div class="bo-form-row"><label for="address_detail" class="bo-form-label">주소</label><div class="bo-form-field"><input type="text" class="board-form-control @error('address_detail') is-invalid @enderror" id="address_detail" name="address_detail" value="{{ old('address_detail', $detail?->address_detail) }}" maxlength="500" placeholder="상세주소를 입력해주세요.">@error('address_detail')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
    <div class="bo-form-row"><label for="venue_name" class="bo-form-label">Venue</label><div class="bo-form-field"><input type="text" class="board-form-control @error('venue_name') is-invalid @enderror" id="venue_name" name="venue_name" value="{{ old('venue_name', $detail?->venue_name) }}" maxlength="255">@error('venue_name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
    <div class="bo-form-row"><label for="venue_description" class="bo-form-label">Venue 상세설명</label><div class="bo-form-field"><textarea class="board-form-control board-form-textarea @error('venue_description') is-invalid @enderror" id="venue_description" name="venue_description" rows="10" data-backoffice-ckeditor data-source-editing="true">{{ old('venue_description', $detail?->venue_description) }}</textarea>@error('venue_description')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
    <div class="bo-form-row"><label for="event_date" class="bo-form-label">Date</label><div class="bo-form-field"><input type="text" class="board-form-control @error('event_date') is-invalid @enderror" id="event_date" name="event_date" value="{{ old('event_date', $detail?->event_date) }}" maxlength="255">@error('event_date')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
    <div class="bo-form-row"><span class="bo-form-label">Format</span><div class="bo-form-field"><div class="board-radio-group">@foreach($formatOptions as $value => $label)<label class="board-radio-item"><input type="radio" name="format" value="{{ $value }}" @checked(old('format', $detail?->format) === $value)> {{ $label }}</label>@endforeach</div>@error('format')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div></div>
    @foreach(['bus_content' => 'BUS', 'subway_content' => 'SUBWAY', 'taxi_content' => 'TAXI'] as $field => $label)
        <div class="bo-form-row"><label for="{{ $field }}" class="bo-form-label">{{ $label }}</label><div class="bo-form-field"><textarea class="board-form-control board-form-textarea @error($field) is-invalid @enderror" id="{{ $field }}" name="{{ $field }}" rows="10" data-backoffice-ckeditor data-source-editing="true">{{ old($field, $detail?->{$field}) }}</textarea>@error($field)<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
    @endforeach
</div></div>
