@extends('backoffice.layouts.app')
@section('title','주소록 관리')
@section('styles')<link rel="stylesheet" href="{{ asset('css/backoffice/boards.css') }}"><link rel="stylesheet" href="{{ asset('css/backoffice/backoffice-crud.css') }}">@endsection
@section('scripts')<script src="{{ asset('js/backoffice/about-pages.js') }}?v={{ filemtime(public_path('js/backoffice/about-pages.js')) }}"></script>@endsection
@section('content')
@if(session('success'))<div class="alert alert-success board-hidden-alert">{{ session('success') }}</div>@endif
<div class="board-container" data-about-page-list data-entity-name="주소록"><div class="board-page-header"><div class="board-page-buttons"><button type="button" id="btnDeleteMultiple" class="btn btn-danger" data-url="{{ route('backoffice.address-books.delete-multiple') }}"><i class="fas fa-trash"></i> 선택 삭제</button><a href="{{ route('backoffice.address-books.create') }}" class="btn btn-success"><i class="fas fa-plus"></i> 신규등록</a></div></div><div class="board-card"><div class="board-card-body">
<div class="board-filter"><form method="GET" class="filter-form"><input type="hidden" name="per_page" value="{{ $perPage }}"><div class="filter-row"><div class="filter-group"><label for="created_from" class="filter-label">등록일 시작</label><input type="date" id="created_from" name="created_from" class="filter-input" value="{{ $filters['created_from']??'' }}"></div><div class="filter-group"><label for="created_to" class="filter-label">등록일 끝</label><input type="date" id="created_to" name="created_to" class="filter-input" value="{{ $filters['created_to']??'' }}"></div><div class="filter-group"><label for="keyword" class="filter-label">검색어</label><input type="text" id="keyword" name="keyword" class="filter-input" placeholder="주소록명, 이름 또는 이메일" value="{{ $filters['keyword']??'' }}"></div><div class="filter-group"><div class="filter-buttons"><button class="btn btn-primary"><i class="fas fa-search"></i> 검색</button><a href="{{ route('backoffice.address-books.index') }}" class="btn btn-secondary"><i class="fas fa-undo"></i> 초기화</a></div></div></div></form></div>
<div class="board-list-header"><div class="list-info"><span class="list-count">Total : {{ $addressBooks->total() }}</span></div><div class="list-controls"><form method="GET" class="per-page-form"><input type="hidden" name="keyword" value="{{ $filters['keyword']??'' }}"><label for="perPageSelect" class="per-page-label">표시 개수:</label><select id="perPageSelect" name="per_page" class="per-page-select" data-auto-submit>@foreach([10,20,50] as $size)<option value="{{ $size }}" @selected($perPage===$size)>{{ $size }}개</option>@endforeach</select></form></div></div>
<div class="table-responsive"><table class="board-table"><thead><tr><th class="w5"><input type="checkbox" id="select-all" class="form-check-input"></th><th>No</th><th>주소록명</th><th>연락처 수</th><th>작성자</th><th>등록일</th><th>관리</th></tr></thead><tbody>@forelse($addressBooks as $index=>$book)<tr><td><input type="checkbox" class="form-check-input bo-row-checkbox" value="{{ $book->id }}"></td><td>{{ $addressBooks->total()-($addressBooks->currentPage()-1)*$addressBooks->perPage()-$index }}</td><td>{{ $book->name }}</td><td>{{ $book->contacts_count }}</td><td>{{ $book->creator?->name??'-' }}</td><td>{{ $book->created_at->format('Y.m.d') }}</td><td><div class="board-btn-group"><a href="{{ route('backoffice.address-books.edit',['addressBook'=>$book,'return_url'=>request()->fullUrl()]) }}" class="btn btn-primary btn-sm"><i class="fas fa-edit"></i> 수정</a><button type="button" class="btn btn-danger btn-sm btn-delete-about-page" data-url="{{ route('backoffice.address-books.destroy',$book) }}"><i class="fas fa-trash"></i> 삭제</button></div></td></tr>@empty<tr><td colspan="7" class="text-center">등록된 주소록이 없습니다.</td></tr>@endforelse</tbody></table></div><x-pagination :paginator="$addressBooks" />
</div></div></div>
@endsection
