@extends('backoffice.layouts.app')
@section('title','신청자 확인')
@section('styles')<link rel="stylesheet" href="{{ asset('css/backoffice/boards.css') }}"><link rel="stylesheet" href="{{ asset('css/backoffice/backoffice-crud.css') }}">@endsection
@section('scripts')<script src="{{ asset('js/backoffice/about-pages.js') }}?v={{ filemtime(public_path('js/backoffice/about-pages.js')) }}"></script>@endsection
@section('content')
@if(session('success'))<div class="alert alert-success board-hidden-alert">{{ session('success') }}</div>@endif
<div class="board-container" data-about-page-list data-entity-name="신청자"><div class="board-page-header"><div class="board-page-buttons"><button type="button" id="btnDeleteMultiple" class="btn btn-danger" data-url="{{ route('backoffice.registration-applicants.delete-multiple') }}"><i class="fas fa-trash"></i> 선택 삭제</button><a href="{{ route('backoffice.registration-applicants.create') }}" class="btn btn-success"><i class="fas fa-plus"></i> 신규등록</a></div></div><div class="board-card"><div class="board-card-body">
<div class="board-filter"><form method="GET" class="filter-form"><input type="hidden" name="per_page" value="{{ $perPage }}"><div class="filter-row"><div class="filter-group"><label for="registration_page_id" class="filter-label">Registration</label><select id="registration_page_id" name="registration_page_id" class="filter-select"><option value="">전체</option>@foreach($registrationPages as $page)<option value="{{ $page->id }}" @selected((string)($filters['registration_page_id']??'')===(string)$page->id)>{{ $page->page_title }}</option>@endforeach</select></div><div class="filter-group"><label for="status" class="filter-label">상태</label><select id="status" name="status" class="filter-select"><option value="">전체</option><option value="pending" @selected(($filters['status']??'')==='pending')>접수</option><option value="approved" @selected(($filters['status']??'')==='approved')>승인</option><option value="cancelled" @selected(($filters['status']??'')==='cancelled')>취소</option></select></div><div class="filter-group"><label for="keyword" class="filter-label">검색어</label><input type="text" id="keyword" name="keyword" class="filter-input" placeholder="이름, 이메일 또는 소속" value="{{ $filters['keyword']??'' }}"></div><div class="filter-group"><div class="filter-buttons"><button class="btn btn-primary"><i class="fas fa-search"></i> 검색</button><a href="{{ route('backoffice.registration-applicants.index') }}" class="btn btn-secondary"><i class="fas fa-undo"></i> 초기화</a></div></div></div></form></div>
<div class="board-list-header"><div class="list-info"><span class="list-count">Total : {{ $applicants->total() }}</span></div><div class="list-controls"><form method="GET" class="per-page-form">@foreach(['registration_page_id','status','keyword'] as $key)<input type="hidden" name="{{ $key }}" value="{{ $filters[$key]??'' }}">@endforeach<label for="perPageSelect" class="per-page-label">표시 개수:</label><select id="perPageSelect" name="per_page" class="per-page-select" data-auto-submit>@foreach([10,20,50] as $size)<option value="{{ $size }}" @selected($perPage===$size)>{{ $size }}개</option>@endforeach</select></form></div></div>
<div class="table-responsive"><table class="board-table"><thead><tr><th class="w5"><input type="checkbox" id="select-all" class="form-check-input"></th><th>No</th><th>Registration</th><th>이름</th><th>이메일</th><th>소속</th><th>상태</th><th>등록일</th><th>관리</th></tr></thead><tbody>@forelse($applicants as $index=>$applicant)<tr><td><input type="checkbox" value="{{ $applicant->id }}" class="form-check-input bo-row-checkbox"></td><td>{{ $applicants->total()-($applicants->currentPage()-1)*$applicants->perPage()-$index }}</td><td>{{ $applicant->registrationPage?->page_title }}</td><td>{{ $applicant->name }}</td><td>{{ $applicant->email }}</td><td>{{ $applicant->affiliation?:'-' }}</td><td>{{ ['pending'=>'접수','approved'=>'승인','cancelled'=>'취소'][$applicant->status]??$applicant->status }}</td><td>{{ $applicant->created_at->format('Y.m.d') }}</td><td><div class="board-btn-group"><a href="{{ route('backoffice.registration-applicants.edit',['registrationApplicant'=>$applicant,'return_url'=>request()->fullUrl()]) }}" class="btn btn-primary btn-sm"><i class="fas fa-edit"></i> 수정</a><button type="button" class="btn btn-danger btn-sm btn-delete-about-page" data-url="{{ route('backoffice.registration-applicants.destroy',$applicant) }}"><i class="fas fa-trash"></i> 삭제</button></div></td></tr>@empty<tr><td colspan="9" class="text-center">등록된 신청자가 없습니다.</td></tr>@endforelse</tbody></table></div><x-pagination :paginator="$applicants" />
</div></div></div>
@endsection
