@php
$mailCampaign=$mailCampaign??null;
$targetType=old('target_type',$mailCampaign?->target_type??'address_book');
$selectedAddressBooks=array_map('intval',(array)old('address_book_ids',$mailCampaign?->addressBooks?->pluck('id')->all()??[]));
$files=(array)($mailCampaign?->attachments??[]);
$removed=array_map('intval',(array)old('remove_attachments',[]));
$visibleCount=count(array_filter(array_keys($files),fn($index)=>!in_array($index,$removed,true)));
@endphp
<div class="bo-form-section"><div class="bo-form-list">
@foreach(['sender_name'=>'발신자명','sender_email'=>'발신 이메일','subject'=>'제목'] as $field=>$label)<div class="bo-form-row"><label for="{{ $field }}" class="bo-form-label">{{ $label }} <span class="required">*</span></label><div class="bo-form-field"><input type="{{ str_contains($field,'email')?'email':'text' }}" class="board-form-control @error($field) is-invalid @enderror" id="{{ $field }}" name="{{ $field }}" value="{{ old($field,$mailCampaign?->{$field}) }}" required>@error($field)<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>@endforeach
<div class="bo-form-row"><span class="bo-form-label">발송대상 <span class="required">*</span></span><div class="bo-form-field"><label class="radio-label"><input type="radio" name="target_type" value="address_book" data-mail-target @checked($targetType==='address_book')> 주소록</label><label class="radio-label"><input type="radio" name="target_type" value="direct" data-mail-target @checked($targetType==='direct')> 직접입력</label>@error('target_type')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div></div>
<div data-mail-address-books @if($targetType!=='address_book') hidden @endif><div class="bo-form-row"><span class="bo-form-label">주소록 <span class="required">*</span></span><div class="bo-form-field"><div class="bo-check-grid">@forelse($addressBooks as $book)<label class="checkbox-label"><input type="checkbox" name="address_book_ids[]" value="{{ $book->id }}" @checked(in_array($book->id,$selectedAddressBooks,true))> {{ $book->name }} ({{ $book->contacts_count }}명)</label>@empty<span class="board-form-help">등록된 주소록이 없습니다.</span>@endforelse</div>@error('address_book_ids')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div></div></div>
<div data-mail-direct @if($targetType!=='direct') hidden @endif><div class="bo-form-row"><label for="direct_recipients" class="bo-form-label">직접입력 <span class="required">*</span></label><div class="bo-form-field"><textarea class="board-form-control board-form-textarea @error('direct_recipients') is-invalid @enderror" id="direct_recipients" name="direct_recipients" rows="6" placeholder="이메일을 줄바꿈, 쉼표 또는 세미콜론으로 구분해주세요.">{{ old('direct_recipients',$mailCampaign?->direct_recipients) }}</textarea>@error('direct_recipients')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div></div>
<div class="bo-form-row"><label for="subscription_status" class="bo-form-label">이메일 수신여부</label><div class="bo-form-field"><select class="board-form-control @error('subscription_status') is-invalid @enderror" id="subscription_status" name="subscription_status"><option value="subscribed" @selected(old('subscription_status',$mailCampaign?->subscription_status??'subscribed')==='subscribed')>수신</option><option value="unsubscribed" @selected(old('subscription_status',$mailCampaign?->subscription_status)==='unsubscribed')>미수신</option></select>@error('subscription_status')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
<div class="bo-form-row"><label for="content" class="bo-form-label">내용 <span class="required">*</span></label><div class="bo-form-field"><textarea class="board-form-control board-form-textarea @error('content') is-invalid @enderror" id="content" name="content" rows="14" data-backoffice-ckeditor data-source-editing="true">{{ old('content',$mailCampaign?->content) }}</textarea>@error('content')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div></div>
<div class="bo-form-row"><label for="attachments" class="bo-form-label">첨부파일</label><div class="bo-form-field bo-about-full-field"><div class="board-file-upload" data-speaker-file-upload data-existing-count="{{ $visibleCount }}"><div class="board-file-input-wrapper"><input type="file" class="board-file-input @if($errors->has('attachments') || $errors->has('attachments.*')) is-invalid @endif" id="attachments" name="attachments[]" data-max-size="20971520" data-max-files="5" multiple><div class="board-file-input-content"><i class="fas fa-cloud-upload-alt"></i><span class="board-file-input-text">파일을 선택하거나 여기로 드래그하세요</span><span class="board-file-input-subtext">최대 5개, 각 파일 20MB 이하</span></div></div><div data-speaker-removed-attachment-inputs>@foreach($removed as $index)<input type="hidden" name="remove_attachments[]" value="{{ $index }}">@endforeach</div>@if($visibleCount>0)<div class="board-existing-files"><div class="board-attachment-list">@foreach($files as $index=>$file)@continue(in_array($index,$removed,true))<div class="board-attachment-item existing-file" data-speaker-existing-attachment><i class="fas fa-file"></i><a href="{{ asset('storage/'.$file['path']) }}" target="_blank" rel="noopener" class="board-attachment-name">{{ $file['name'] }}</a><button type="button" class="board-attachment-remove" data-speaker-existing-attachment-remove data-index="{{ $index }}" aria-label="기존 첨부파일 삭제"><i class="fas fa-times"></i></button></div>@endforeach</div></div>@endif<div class="board-file-preview" data-speaker-file-preview></div></div>@error('attachments')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror @error('attachments.*')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div></div>
</div></div>
