@extends('backoffice.layouts.app')
@section('title','메일 발송')
@section('styles')<link rel="stylesheet" href="{{ asset('css/backoffice/boards.css') }}"><link rel="stylesheet" href="{{ asset('css/backoffice/backoffice-crud.css') }}">@endsection
@section('scripts')<script src="{{ asset('js/backoffice/about-pages.js') }}?v={{ filemtime(public_path('js/backoffice/about-pages.js')) }}"></script><script src="{{ asset('js/backoffice/mail-campaigns.js') }}?v={{ filemtime(public_path('js/backoffice/mail-campaigns.js')) }}"></script>@endsection
@section('content')
@if(session('success'))<div class="alert alert-success board-hidden-alert">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger board-hidden-alert">{{ $errors->first() }}</div>@endif
<div class="board-container" data-about-page-list data-entity-name="메일"><div class="board-page-header"><div class="board-page-buttons"><button type="button" id="btnDeleteMultiple" class="btn btn-danger" data-url="{{ route('backoffice.mail-campaigns.delete-multiple') }}"><i class="fas fa-trash"></i> 선택 삭제</button><a href="{{ route('backoffice.mail-campaigns.create') }}" class="btn btn-success"><i class="fas fa-plus"></i> 신규등록</a></div></div><div class="board-card"><div class="board-card-body">
<div class="board-filter"><form method="GET" class="filter-form"><input type="hidden" name="per_page" value="{{ $perPage }}"><div class="filter-row"><div class="filter-group"><label for="status" class="filter-label">발송 상태</label><select id="status" name="status" class="filter-select"><option value="">전체</option>@foreach(['draft'=>'임시저장','queued'=>'대기','sending'=>'발송중','sent'=>'완료','partial'=>'일부실패','failed'=>'실패'] as $value=>$label)<option value="{{ $value }}" @selected(($filters['status']??'')===$value)>{{ $label }}</option>@endforeach</select></div><div class="filter-group"><label for="created_from" class="filter-label">등록일 시작</label><input type="date" id="created_from" name="created_from" class="filter-input" value="{{ $filters['created_from']??'' }}"></div><div class="filter-group"><label for="created_to" class="filter-label">등록일 끝</label><input type="date" id="created_to" name="created_to" class="filter-input" value="{{ $filters['created_to']??'' }}"></div><div class="filter-group"><label for="keyword" class="filter-label">검색어</label><input type="text" id="keyword" name="keyword" class="filter-input" placeholder="제목 또는 발신자" value="{{ $filters['keyword']??'' }}"></div><div class="filter-group"><div class="filter-buttons"><button class="btn btn-primary"><i class="fas fa-search"></i> 검색</button><a href="{{ route('backoffice.mail-campaigns.index') }}" class="btn btn-secondary"><i class="fas fa-undo"></i> 초기화</a></div></div></div></form></div>
<div class="board-list-header"><div class="list-info"><span class="list-count">Total : {{ $campaigns->total() }}</span></div><div class="list-controls"><form method="GET" class="per-page-form"><input type="hidden" name="status" value="{{ $filters['status']??'' }}"><input type="hidden" name="keyword" value="{{ $filters['keyword']??'' }}"><label for="perPageSelect" class="per-page-label">표시 개수:</label><select id="perPageSelect" name="per_page" class="per-page-select" data-auto-submit>@foreach([10,20,50] as $size)<option value="{{ $size }}" @selected($perPage===$size)>{{ $size }}개</option>@endforeach</select></form></div></div>
<div class="table-responsive"><table class="board-table"><thead><tr><th class="w5"><input type="checkbox" id="select-all" class="form-check-input"></th><th>No</th><th>제목</th><th>발신자</th><th>발송대상</th><th>상태</th><th>수신자 수</th><th>등록일</th><th>관리</th></tr></thead><tbody>@forelse($campaigns as $index=>$campaign)<tr><td><input type="checkbox" class="form-check-input bo-row-checkbox" value="{{ $campaign->id }}"></td><td>{{ $campaigns->total()-($campaigns->currentPage()-1)*$campaigns->perPage()-$index }}</td><td>{{ $campaign->subject }}</td><td>{{ $campaign->sender_name }}<br>{{ $campaign->sender_email }}</td><td>{{ $campaign->target_type==='address_book'?'주소록':'직접입력' }}</td><td>{{ ['draft'=>'임시저장','queued'=>'대기','sending'=>'발송중','sent'=>'완료','partial'=>'일부실패','failed'=>'실패'][$campaign->status]??$campaign->status }}</td><td>{{ $campaign->recipients_count }}</td><td>{{ $campaign->created_at->format('Y.m.d') }}</td><td><div class="board-btn-group"><a href="{{ route('backoffice.mail-campaigns.edit',['mailCampaign'=>$campaign,'return_url'=>request()->fullUrl()]) }}" class="btn btn-primary btn-sm"><i class="fas fa-edit"></i> 수정</a>@if(in_array($campaign->status,['draft','failed','partial']))<form method="POST" action="{{ route('backoffice.mail-campaigns.send',$campaign) }}" data-mail-send-form>@csrf<button class="btn btn-success btn-sm"><i class="fas fa-paper-plane"></i> 발송</button></form>@endif<button type="button" class="btn btn-danger btn-sm btn-delete-about-page" data-url="{{ route('backoffice.mail-campaigns.destroy',$campaign) }}"><i class="fas fa-trash"></i> 삭제</button></div></td></tr>@empty<tr><td colspan="9" class="text-center">등록된 메일이 없습니다.</td></tr>@endforelse</tbody></table></div><x-pagination :paginator="$campaigns" />
</div></div></div>
@endsection
